# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .bucket import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "nuage",
  "mod": "index",
  "fqn": "pulumi_nuage",
  "classes": {
   "nuage:index:bucket": "Bucket"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "nuage",
  "token": "pulumi:providers:nuage",
  "fqn": "pulumi_nuage",
  "class": "Provider"
 }
]
"""
)
