version: "3"

tasks:
  sdk:
    desc: Generates SDKs
    cmds:
      - make generate
    sources:
      - provider/cmd/pulumi-resource-nuage/nuage_provider/*.py
      - provider/cmd/pulumi-resource-nuage/requirements.txt
      - schema.json
    generates:
      - sdk/**/*

  build:
    desc: Build binaries for each SDK
    deps:
      - sdk
    cmds:
      - make build
      # - make install
    sources:
      - sdk/**/*
    generates:
      - bin/**/*
      - provider/cmd/pulumi-resource-nuage/build/**/*
      - provider/cmd/pulumi-resource-nuage/nuage_provider.egg-info/*

  test:
    desc: Run python integration tests.
    deps:
      - install
    cmds:
      - pytest --capture=sys provider/cmd/pulumi-resource-nuage/pytests/tests/ -s

  install:
    desc: Install requirements for integration tests.
    deps:
      - virtualenv
    cmds:
      - provider/cmd/pulumi-resource-nuage/pytests/venv/bin/pip install -r provider/cmd/pulumi-resource-nuage/pytests/requirements.txt
    sources:
      - ./provider/cmd/pulumi-resource-nuage/pytests/requirements.txt

  virtualenv:
    desc: Creates a virtualenv for integration tests.
    cmds:
      - python3 -m venv provider/cmd/pulumi-resource-nuage/pytests/venv
    status:
      - test -d provider/cmd/pulumi-resource-nuage/pytests/venv
