version: "3"

includes:
  test:
    dir: ./provider/cmd/tests/
    taskfile: ./provider/cmd/tests/TestTasks.yml

env:
  versionNumber:
    sh: cat schema.json | jq -r '.version'

tasks:
  sdk:
    desc: Generates SDKs
    cmds:
      - make generate
    sources:
      - provider/cmd/pulumi-resource-nuage/nuage_provider/*.py
      - provider/cmd/pulumi-resource-nuage/requirements.txt
      - schema.json
    generates:
      - sdk/**/*

  build:
    desc: Build binaries for each SDK
    deps:
      - sdk
    cmds:
      - make build
      # - make install
    sources:
      - sdk/**/*
    generates:
      - bin/**/*
      - provider/cmd/pulumi-resource-nuage/build/**/*
      - provider/cmd/pulumi-resource-nuage/nuage_provider.egg-info/*

  distribute:
    desc: Create Distribution
    deps:
      - build
    cmds:
      - make dist

  install-local:
    desc: Install Project locally
    deps:
      - distribute
    vars:
      IMAGE_NAME: $(sh DetectPlatformName.sh)
    cmds:
      - make install
      - pulumi plugin rm resource nuage -y
      - pulumi plugin install resource nuage ${versionNumber} --file dist/pulumi-resource-nuage-v${versionNumber}-{{.IMAGE_NAME}}.tar.gz
