version: "3"

includes:
  test:
    dir: ./provider/cmd/tests/
    taskfile: ./provider/cmd/tests/TestTasks.yml

tasks:
  sdk:
    desc: Generates SDKs
    cmds:
      - make generate
    sources:
      - provider/cmd/pulumi-resource-nuage/nuage_provider/*.py
      - provider/cmd/pulumi-resource-nuage/requirements.txt
      - schema.json
    generates:
      - sdk/**/*

  build:
    desc: Build binaries for each SDK
    deps:
      - sdk
    cmds:
      - make build
      # - make install
    sources:
      - sdk/**/*
    generates:
      - bin/**/*
      - provider/cmd/pulumi-resource-nuage/build/**/*
      - provider/cmd/pulumi-resource-nuage/nuage_provider.egg-info/*
