// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Bastion extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'nuage:aws:Bastion';

    /**
     * Returns true if the given object is an instance of Bastion.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Bastion {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Bastion.__pulumiType;
    }

    public /*out*/ readonly private_key_pem!: pulumi.Output<string>;
    public /*out*/ readonly public_ip!: pulumi.Output<string>;

    /**
     * Create a Bastion resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BastionArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.vpcId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'vpcId'");
            }
            if ((!args || args.vpcSubnets === undefined) && !opts.urn) {
                throw new Error("Missing required property 'vpcSubnets'");
            }
            resourceInputs["sshPort"] = args ? args.sshPort : undefined;
            resourceInputs["vpcId"] = args ? args.vpcId : undefined;
            resourceInputs["vpcSubnets"] = args ? args.vpcSubnets : undefined;
            resourceInputs["private_key_pem"] = undefined /*out*/;
            resourceInputs["public_ip"] = undefined /*out*/;
        } else {
            resourceInputs["private_key_pem"] = undefined /*out*/;
            resourceInputs["public_ip"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Bastion.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Bastion resource.
 */
export interface BastionArgs {
    /**
     * Ssh port for bastion host. Defaults to 22
     */
    sshPort?: pulumi.Input<number>;
    /**
     * Vpc id.
     */
    vpcId: pulumi.Input<string>;
    /**
     * List of subnet ip addresses of Vpc.
     */
    vpcSubnets: pulumi.Input<pulumi.Input<string>[]>;
}
