// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../types";
import * as utilities from "../utilities";

import * as pulumiAws from "@pulumi/aws";

/**
 * Provides an AWS Lambda Function with additional necesary resources. It bundles several resources such as `Lambda Functions`, `Function URLs`, `CloudWatch keep-warm rules`, `Log Group with a Retention Policy`, `Role to run Lambda and Write Logs`. It also has a feature for schedule (cron) definitions and automated X-Ray tracing.
 *
 * ## Example Usage
 */
export class ContainerFunction extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'nuage:aws:ContainerFunction';

    /**
     * Returns true if the given object is an instance of ContainerFunction.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ContainerFunction {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ContainerFunction.__pulumiType;
    }

    /**
     * ARN (Amazon Resource Name) of the Lambda Function.
     */
    public /*out*/ readonly arn!: pulumi.Output<string>;
    /**
     * Name of the Lambda Function.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Lambda Function URL (Only valid if `urlEnabled` is used).
     */
    public /*out*/ readonly url!: pulumi.Output<string | undefined>;

    /**
     * Create a ContainerFunction resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ContainerFunctionArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.imageUri === undefined) && !opts.urn) {
                throw new Error("Missing required property 'imageUri'");
            }
            resourceInputs["architecture"] = args ? args.architecture : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["environment"] = args ? args.environment : undefined;
            resourceInputs["imageUri"] = args ? args.imageUri : undefined;
            resourceInputs["keepWarm"] = args ? args.keepWarm : undefined;
            resourceInputs["logRetentionInDays"] = args ? args.logRetentionInDays : undefined;
            resourceInputs["memorySize"] = args ? args.memorySize : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["namePrefix"] = args ? args.namePrefix : undefined;
            resourceInputs["policyDocument"] = args ? args.policyDocument : undefined;
            resourceInputs["scheduleConfig"] = args ? args.scheduleConfig : undefined;
            resourceInputs["timeout"] = args ? args.timeout : undefined;
            resourceInputs["urlConfig"] = args ? args.urlConfig : undefined;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        } else {
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ContainerFunction.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a ContainerFunction resource.
 */
export interface ContainerFunctionArgs {
    /**
     * Architecture, either `X86_64` or `ARM64`. Defaults to `X86_64`
     */
    architecture?: pulumi.Input<string>;
    /**
     * Description of the function.
     */
    description?: pulumi.Input<string>;
    /**
     * Environment Variables
     */
    environment?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Image uri of the docker image.
     */
    imageUri: pulumi.Input<string>;
    /**
     * Keep warm by refreshing the lambda function every 5 minutes. Defaults to `false`
     */
    keepWarm?: pulumi.Input<boolean>;
    /**
     * Number of days for log retention to pass in cloudwatch log group. Defaults to `90`
     */
    logRetentionInDays?: pulumi.Input<number>;
    /**
     * Amount of memory in MB your Lambda Function can use at runtime. Defaults to `512`.
     */
    memorySize?: pulumi.Input<number>;
    /**
     * Name of the resource.
     */
    name?: pulumi.Input<string>;
    /**
     * Name prefix as an alternative to name and adds random suffix at the end.
     */
    namePrefix?: pulumi.Input<string>;
    /**
     * Policy Document for lambda.
     */
    policyDocument?: pulumi.Input<string>;
    /**
     * Configure the function's cloudwatch event rule schedule.
     */
    scheduleConfig?: pulumi.Input<inputs.aws.FunctionScheduleArgs>;
    /**
     * Amount of time your Lambda Function has to run in seconds. Defaults to `3`
     */
    timeout?: pulumi.Input<number>;
    /**
     * Configure lambda function url.
     */
    urlConfig?: pulumi.Input<inputs.aws.FunctionUrlArgs>;
}
