// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Provides an AWS Lambda Function with additional necesary resources. It bundles several resources such as `Lambda Functions`, `Function URLs`, `CloudWatch keep-warm rules`, `Log Group with a Retention Policy`, `Role to run Lambda and Write Logs`. It also has a feature to manage build and deployment of Docker builds, removal of docker build artifacts (randomly generated image names that pollute your local docker) and automated X-Ray tracing.
 *
 * ## Example Usage
 */
export class ContainerFunction extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'nuage:aws:ContainerFunction';

    /**
     * Returns true if the given object is an instance of ContainerFunction.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ContainerFunction {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ContainerFunction.__pulumiType;
    }

    public /*out*/ readonly arn!: pulumi.Output<string>;
    public /*out*/ readonly function_url!: pulumi.Output<string>;
    public /*out*/ readonly image_uri!: pulumi.Output<string>;
    public readonly name!: pulumi.Output<string>;

    /**
     * Create a ContainerFunction resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ContainerFunctionArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.repositoryUrl === undefined) && !opts.urn) {
                throw new Error("Missing required property 'repositoryUrl'");
            }
            resourceInputs["architecture"] = args ? args.architecture : undefined;
            resourceInputs["context"] = args ? args.context : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["dockerfile"] = args ? args.dockerfile : undefined;
            resourceInputs["environment"] = args ? args.environment : undefined;
            resourceInputs["keepWarm"] = args ? args.keepWarm : undefined;
            resourceInputs["logRetentionInDays"] = args ? args.logRetentionInDays : undefined;
            resourceInputs["memorySize"] = args ? args.memorySize : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["namePrefix"] = args ? args.namePrefix : undefined;
            resourceInputs["policyDocument"] = args ? args.policyDocument : undefined;
            resourceInputs["repositoryUrl"] = args ? args.repositoryUrl : undefined;
            resourceInputs["timeout"] = args ? args.timeout : undefined;
            resourceInputs["url"] = args ? args.url : undefined;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["function_url"] = undefined /*out*/;
            resourceInputs["image_uri"] = undefined /*out*/;
        } else {
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["function_url"] = undefined /*out*/;
            resourceInputs["image_uri"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ContainerFunction.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a ContainerFunction resource.
 */
export interface ContainerFunctionArgs {
    /**
     * Architecture, either `X86_64` or `ARM64`. Defaults to `X86_64`
     */
    architecture?: pulumi.Input<string>;
    /**
     * Dockerfile context path.
     */
    context?: pulumi.Input<string>;
    /**
     * Description of the function.
     */
    description?: pulumi.Input<string>;
    /**
     * Dockerfile path. Defaults to `./Dockerfile`
     */
    dockerfile?: pulumi.Input<string>;
    /**
     * Environment Variables
     */
    environment?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Keep warm by refreshing the lambda function every 5 minutes. Defaults to `false`
     */
    keepWarm?: pulumi.Input<boolean>;
    /**
     * Number of days for log retention to pass in cloudwatch log group..
     */
    logRetentionInDays?: pulumi.Input<number>;
    /**
     * Amount of memory in MB your Lambda Function can use at runtime. Defaults to `512`.
     */
    memorySize?: pulumi.Input<number>;
    /**
     * Name of the resource.
     */
    name?: pulumi.Input<string>;
    /**
     * Name prefix as an alternative to name and adds random suffix at the end.
     */
    namePrefix?: pulumi.Input<string>;
    /**
     * Policy Document for lambda.
     */
    policyDocument?: pulumi.Input<string>;
    /**
     * Existing ECR repository name
     */
    repositoryUrl: pulumi.Input<string>;
    /**
     * Amount of time your Lambda Function has to run in seconds. Defaults to `3`
     */
    timeout?: pulumi.Input<number>;
    /**
     * Use Lambda URL. Defaults to `false`
     */
    url?: pulumi.Input<boolean>;
}
