// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./bucket_nuage";
export * from "./containerFunction";

// Export enums:
export * from "../types/enums/aws";

// Import resources to register:
import { ContainerFunction } from "./containerFunction";
import { Bucket_nuage } from "./bucket_nuage";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "nuage:aws:ContainerFunction":
                return new ContainerFunction(name, <any>undefined, { urn })
            case "nuage:aws:bucket_nuage":
                return new Bucket_nuage(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("nuage", "aws", _module)
