# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'ArchitectureType',
]


class ArchitectureType(str, Enum):
    """
    Architecture, either 'X86_64' or 'arm64'.
    """
    X86_64 = "X86_64"
    """
    X86_64 architecture.
    """
    ARM64 = "ARM64"
    """
    ARM64 architecture.
    """
