version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    init: true
    volumes:
      - ..:/workspace:cached
      # AWS credentials
      - ~/.aws:/home/vscode/.aws:cached
      # Pulumi credentials,
      - ~/.pulumi/credentials.json:/home/vscode/.pulumi/credentials.json:cached
      # Ssh credentials for GitHub
      - ~/.ssh:/home/vscode/.ssh:cached
      # Docker from Docker
      - /var/run/docker.sock:/var/run/docker-host.sock

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  localstack:
    image: localstack/localstack:2.0.1
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "../.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
