version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "3.10"
    init: true
    volumes:
      - ..:/workspace:cached
      # AWS credentials
      - ~/.aws:/home/vscode/.aws:cached
      # Pulumi credentials, We set PULUMI_MOUNT_DIR to overwrite or ignore this.
      - ~/.pulumi:${PULUMI_MOUNT_DIR:-/home/vscode/.pulumi}:cached
      # Ssh credentials for GitHub
      - ~/.ssh:/home/vscode/.ssh:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
