// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aws

// Architecture, either 'X86_64' or 'arm64'.
type ArchitectureType string

const (
	// X86_64 architecture.
	ArchitectureType_X86_64 = ArchitectureType("X86_64")
	// ARM64 architecture.
	ArchitectureTypeARM64 = ArchitectureType("ARM64")
)

func init() {
}
