// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aws

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/lambda"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type DockerBuild struct {
	// Architecture, either `X86_64` or `ARM64`. Defaults to `X86_64`
	Architecture *string `pulumi:"architecture"`
	// The path to the build context to use.
	Context *string `pulumi:"context"`
	// The path to the Dockerfile to use.
	Dockerfile *string `pulumi:"dockerfile"`
	// Environment variables to set on the invocation of docker build, for example to support DOCKER_BUILDKIT=1 docker build.
	Env map[string]string `pulumi:"env"`
	// A bag of extra options to pass on to the docker SDK.
	ExtraOptions []string `pulumi:"extraOptions"`
	// The target of the Dockerfile to build
	Target *string `pulumi:"target"`
}

// DockerBuildInput is an input type that accepts DockerBuildArgs and DockerBuildOutput values.
// You can construct a concrete instance of `DockerBuildInput` via:
//
//	DockerBuildArgs{...}
type DockerBuildInput interface {
	pulumi.Input

	ToDockerBuildOutput() DockerBuildOutput
	ToDockerBuildOutputWithContext(context.Context) DockerBuildOutput
}

type DockerBuildArgs struct {
	// Architecture, either `X86_64` or `ARM64`. Defaults to `X86_64`
	Architecture pulumi.StringPtrInput `pulumi:"architecture"`
	// The path to the build context to use.
	Context pulumi.StringPtrInput `pulumi:"context"`
	// The path to the Dockerfile to use.
	Dockerfile pulumi.StringPtrInput `pulumi:"dockerfile"`
	// Environment variables to set on the invocation of docker build, for example to support DOCKER_BUILDKIT=1 docker build.
	Env pulumi.StringMapInput `pulumi:"env"`
	// A bag of extra options to pass on to the docker SDK.
	ExtraOptions pulumi.StringArrayInput `pulumi:"extraOptions"`
	// The target of the Dockerfile to build
	Target pulumi.StringPtrInput `pulumi:"target"`
}

func (DockerBuildArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DockerBuild)(nil)).Elem()
}

func (i DockerBuildArgs) ToDockerBuildOutput() DockerBuildOutput {
	return i.ToDockerBuildOutputWithContext(context.Background())
}

func (i DockerBuildArgs) ToDockerBuildOutputWithContext(ctx context.Context) DockerBuildOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DockerBuildOutput)
}

type DockerBuildOutput struct{ *pulumi.OutputState }

func (DockerBuildOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DockerBuild)(nil)).Elem()
}

func (o DockerBuildOutput) ToDockerBuildOutput() DockerBuildOutput {
	return o
}

func (o DockerBuildOutput) ToDockerBuildOutputWithContext(ctx context.Context) DockerBuildOutput {
	return o
}

// Architecture, either `X86_64` or `ARM64`. Defaults to `X86_64`
func (o DockerBuildOutput) Architecture() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DockerBuild) *string { return v.Architecture }).(pulumi.StringPtrOutput)
}

// The path to the build context to use.
func (o DockerBuildOutput) Context() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DockerBuild) *string { return v.Context }).(pulumi.StringPtrOutput)
}

// The path to the Dockerfile to use.
func (o DockerBuildOutput) Dockerfile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DockerBuild) *string { return v.Dockerfile }).(pulumi.StringPtrOutput)
}

// Environment variables to set on the invocation of docker build, for example to support DOCKER_BUILDKIT=1 docker build.
func (o DockerBuildOutput) Env() pulumi.StringMapOutput {
	return o.ApplyT(func(v DockerBuild) map[string]string { return v.Env }).(pulumi.StringMapOutput)
}

// A bag of extra options to pass on to the docker SDK.
func (o DockerBuildOutput) ExtraOptions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v DockerBuild) []string { return v.ExtraOptions }).(pulumi.StringArrayOutput)
}

// The target of the Dockerfile to build
func (o DockerBuildOutput) Target() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DockerBuild) *string { return v.Target }).(pulumi.StringPtrOutput)
}

type FunctionSchedule struct {
	// Expression for creating a cloudwatch event rule.
	ScheduleExpression string `pulumi:"scheduleExpression"`
	// Input for cloudwatch event target.
	ScheduleInput map[string]string `pulumi:"scheduleInput"`
}

// FunctionScheduleInput is an input type that accepts FunctionScheduleArgs and FunctionScheduleOutput values.
// You can construct a concrete instance of `FunctionScheduleInput` via:
//
//	FunctionScheduleArgs{...}
type FunctionScheduleInput interface {
	pulumi.Input

	ToFunctionScheduleOutput() FunctionScheduleOutput
	ToFunctionScheduleOutputWithContext(context.Context) FunctionScheduleOutput
}

type FunctionScheduleArgs struct {
	// Expression for creating a cloudwatch event rule.
	ScheduleExpression pulumi.StringInput `pulumi:"scheduleExpression"`
	// Input for cloudwatch event target.
	ScheduleInput pulumi.StringMapInput `pulumi:"scheduleInput"`
}

func (FunctionScheduleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*FunctionSchedule)(nil)).Elem()
}

func (i FunctionScheduleArgs) ToFunctionScheduleOutput() FunctionScheduleOutput {
	return i.ToFunctionScheduleOutputWithContext(context.Background())
}

func (i FunctionScheduleArgs) ToFunctionScheduleOutputWithContext(ctx context.Context) FunctionScheduleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FunctionScheduleOutput)
}

func (i FunctionScheduleArgs) ToFunctionSchedulePtrOutput() FunctionSchedulePtrOutput {
	return i.ToFunctionSchedulePtrOutputWithContext(context.Background())
}

func (i FunctionScheduleArgs) ToFunctionSchedulePtrOutputWithContext(ctx context.Context) FunctionSchedulePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FunctionScheduleOutput).ToFunctionSchedulePtrOutputWithContext(ctx)
}

// FunctionSchedulePtrInput is an input type that accepts FunctionScheduleArgs, FunctionSchedulePtr and FunctionSchedulePtrOutput values.
// You can construct a concrete instance of `FunctionSchedulePtrInput` via:
//
//	        FunctionScheduleArgs{...}
//
//	or:
//
//	        nil
type FunctionSchedulePtrInput interface {
	pulumi.Input

	ToFunctionSchedulePtrOutput() FunctionSchedulePtrOutput
	ToFunctionSchedulePtrOutputWithContext(context.Context) FunctionSchedulePtrOutput
}

type functionSchedulePtrType FunctionScheduleArgs

func FunctionSchedulePtr(v *FunctionScheduleArgs) FunctionSchedulePtrInput {
	return (*functionSchedulePtrType)(v)
}

func (*functionSchedulePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**FunctionSchedule)(nil)).Elem()
}

func (i *functionSchedulePtrType) ToFunctionSchedulePtrOutput() FunctionSchedulePtrOutput {
	return i.ToFunctionSchedulePtrOutputWithContext(context.Background())
}

func (i *functionSchedulePtrType) ToFunctionSchedulePtrOutputWithContext(ctx context.Context) FunctionSchedulePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FunctionSchedulePtrOutput)
}

type FunctionScheduleOutput struct{ *pulumi.OutputState }

func (FunctionScheduleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*FunctionSchedule)(nil)).Elem()
}

func (o FunctionScheduleOutput) ToFunctionScheduleOutput() FunctionScheduleOutput {
	return o
}

func (o FunctionScheduleOutput) ToFunctionScheduleOutputWithContext(ctx context.Context) FunctionScheduleOutput {
	return o
}

func (o FunctionScheduleOutput) ToFunctionSchedulePtrOutput() FunctionSchedulePtrOutput {
	return o.ToFunctionSchedulePtrOutputWithContext(context.Background())
}

func (o FunctionScheduleOutput) ToFunctionSchedulePtrOutputWithContext(ctx context.Context) FunctionSchedulePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v FunctionSchedule) *FunctionSchedule {
		return &v
	}).(FunctionSchedulePtrOutput)
}

// Expression for creating a cloudwatch event rule.
func (o FunctionScheduleOutput) ScheduleExpression() pulumi.StringOutput {
	return o.ApplyT(func(v FunctionSchedule) string { return v.ScheduleExpression }).(pulumi.StringOutput)
}

// Input for cloudwatch event target.
func (o FunctionScheduleOutput) ScheduleInput() pulumi.StringMapOutput {
	return o.ApplyT(func(v FunctionSchedule) map[string]string { return v.ScheduleInput }).(pulumi.StringMapOutput)
}

type FunctionSchedulePtrOutput struct{ *pulumi.OutputState }

func (FunctionSchedulePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FunctionSchedule)(nil)).Elem()
}

func (o FunctionSchedulePtrOutput) ToFunctionSchedulePtrOutput() FunctionSchedulePtrOutput {
	return o
}

func (o FunctionSchedulePtrOutput) ToFunctionSchedulePtrOutputWithContext(ctx context.Context) FunctionSchedulePtrOutput {
	return o
}

func (o FunctionSchedulePtrOutput) Elem() FunctionScheduleOutput {
	return o.ApplyT(func(v *FunctionSchedule) FunctionSchedule {
		if v != nil {
			return *v
		}
		var ret FunctionSchedule
		return ret
	}).(FunctionScheduleOutput)
}

// Expression for creating a cloudwatch event rule.
func (o FunctionSchedulePtrOutput) ScheduleExpression() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FunctionSchedule) *string {
		if v == nil {
			return nil
		}
		return &v.ScheduleExpression
	}).(pulumi.StringPtrOutput)
}

// Input for cloudwatch event target.
func (o FunctionSchedulePtrOutput) ScheduleInput() pulumi.StringMapOutput {
	return o.ApplyT(func(v *FunctionSchedule) map[string]string {
		if v == nil {
			return nil
		}
		return v.ScheduleInput
	}).(pulumi.StringMapOutput)
}

type FunctionUrl struct {
	// CORS Configuration.
	CorsConfiguration *lambda.FunctionUrlCors `pulumi:"corsConfiguration"`
	// Use Lambda URL. Defaults to `false`
	UrlEnabled *bool `pulumi:"urlEnabled"`
}

// FunctionUrlInput is an input type that accepts FunctionUrlArgs and FunctionUrlOutput values.
// You can construct a concrete instance of `FunctionUrlInput` via:
//
//	FunctionUrlArgs{...}
type FunctionUrlInput interface {
	pulumi.Input

	ToFunctionUrlOutput() FunctionUrlOutput
	ToFunctionUrlOutputWithContext(context.Context) FunctionUrlOutput
}

type FunctionUrlArgs struct {
	// CORS Configuration.
	CorsConfiguration lambda.FunctionUrlCorsPtrInput `pulumi:"corsConfiguration"`
	// Use Lambda URL. Defaults to `false`
	UrlEnabled pulumi.BoolPtrInput `pulumi:"urlEnabled"`
}

func (FunctionUrlArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*FunctionUrl)(nil)).Elem()
}

func (i FunctionUrlArgs) ToFunctionUrlOutput() FunctionUrlOutput {
	return i.ToFunctionUrlOutputWithContext(context.Background())
}

func (i FunctionUrlArgs) ToFunctionUrlOutputWithContext(ctx context.Context) FunctionUrlOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FunctionUrlOutput)
}

func (i FunctionUrlArgs) ToFunctionUrlPtrOutput() FunctionUrlPtrOutput {
	return i.ToFunctionUrlPtrOutputWithContext(context.Background())
}

func (i FunctionUrlArgs) ToFunctionUrlPtrOutputWithContext(ctx context.Context) FunctionUrlPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FunctionUrlOutput).ToFunctionUrlPtrOutputWithContext(ctx)
}

// FunctionUrlPtrInput is an input type that accepts FunctionUrlArgs, FunctionUrlPtr and FunctionUrlPtrOutput values.
// You can construct a concrete instance of `FunctionUrlPtrInput` via:
//
//	        FunctionUrlArgs{...}
//
//	or:
//
//	        nil
type FunctionUrlPtrInput interface {
	pulumi.Input

	ToFunctionUrlPtrOutput() FunctionUrlPtrOutput
	ToFunctionUrlPtrOutputWithContext(context.Context) FunctionUrlPtrOutput
}

type functionUrlPtrType FunctionUrlArgs

func FunctionUrlPtr(v *FunctionUrlArgs) FunctionUrlPtrInput {
	return (*functionUrlPtrType)(v)
}

func (*functionUrlPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**FunctionUrl)(nil)).Elem()
}

func (i *functionUrlPtrType) ToFunctionUrlPtrOutput() FunctionUrlPtrOutput {
	return i.ToFunctionUrlPtrOutputWithContext(context.Background())
}

func (i *functionUrlPtrType) ToFunctionUrlPtrOutputWithContext(ctx context.Context) FunctionUrlPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FunctionUrlPtrOutput)
}

type FunctionUrlOutput struct{ *pulumi.OutputState }

func (FunctionUrlOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*FunctionUrl)(nil)).Elem()
}

func (o FunctionUrlOutput) ToFunctionUrlOutput() FunctionUrlOutput {
	return o
}

func (o FunctionUrlOutput) ToFunctionUrlOutputWithContext(ctx context.Context) FunctionUrlOutput {
	return o
}

func (o FunctionUrlOutput) ToFunctionUrlPtrOutput() FunctionUrlPtrOutput {
	return o.ToFunctionUrlPtrOutputWithContext(context.Background())
}

func (o FunctionUrlOutput) ToFunctionUrlPtrOutputWithContext(ctx context.Context) FunctionUrlPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v FunctionUrl) *FunctionUrl {
		return &v
	}).(FunctionUrlPtrOutput)
}

// CORS Configuration.
func (o FunctionUrlOutput) CorsConfiguration() lambda.FunctionUrlCorsPtrOutput {
	return o.ApplyT(func(v FunctionUrl) *lambda.FunctionUrlCors { return v.CorsConfiguration }).(lambda.FunctionUrlCorsPtrOutput)
}

// Use Lambda URL. Defaults to `false`
func (o FunctionUrlOutput) UrlEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v FunctionUrl) *bool { return v.UrlEnabled }).(pulumi.BoolPtrOutput)
}

type FunctionUrlPtrOutput struct{ *pulumi.OutputState }

func (FunctionUrlPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FunctionUrl)(nil)).Elem()
}

func (o FunctionUrlPtrOutput) ToFunctionUrlPtrOutput() FunctionUrlPtrOutput {
	return o
}

func (o FunctionUrlPtrOutput) ToFunctionUrlPtrOutputWithContext(ctx context.Context) FunctionUrlPtrOutput {
	return o
}

func (o FunctionUrlPtrOutput) Elem() FunctionUrlOutput {
	return o.ApplyT(func(v *FunctionUrl) FunctionUrl {
		if v != nil {
			return *v
		}
		var ret FunctionUrl
		return ret
	}).(FunctionUrlOutput)
}

// CORS Configuration.
func (o FunctionUrlPtrOutput) CorsConfiguration() lambda.FunctionUrlCorsPtrOutput {
	return o.ApplyT(func(v *FunctionUrl) *lambda.FunctionUrlCors {
		if v == nil {
			return nil
		}
		return v.CorsConfiguration
	}).(lambda.FunctionUrlCorsPtrOutput)
}

// Use Lambda URL. Defaults to `false`
func (o FunctionUrlPtrOutput) UrlEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *FunctionUrl) *bool {
		if v == nil {
			return nil
		}
		return v.UrlEnabled
	}).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DockerBuildInput)(nil)).Elem(), DockerBuildArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*FunctionScheduleInput)(nil)).Elem(), FunctionScheduleArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*FunctionSchedulePtrInput)(nil)).Elem(), FunctionScheduleArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*FunctionUrlInput)(nil)).Elem(), FunctionUrlArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*FunctionUrlPtrInput)(nil)).Elem(), FunctionUrlArgs{})
	pulumi.RegisterOutputType(DockerBuildOutput{})
	pulumi.RegisterOutputType(FunctionScheduleOutput{})
	pulumi.RegisterOutputType(FunctionSchedulePtrOutput{})
	pulumi.RegisterOutputType(FunctionUrlOutput{})
	pulumi.RegisterOutputType(FunctionUrlPtrOutput{})
}
