// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aws

// Architecture, either 'x86_64' or 'arm64'.
type ArchitectureType string

const (
	// x86_64 architecture.
	ArchitectureType_X86_64 = ArchitectureType("x86_64")
	// Arm64 architecture.
	ArchitectureTypeArm64 = ArchitectureType("arm64")
)

func init() {
}
