// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const ArchitectureType = {
    /**
     * x86_64 architecture.
     */
    X86_64: "x86_64",
    /**
     * Arm64 architecture.
     */
    Arm64: "arm64",
} as const;

/**
 * Architecture, either 'x86_64' or 'arm64'.
 */
export type ArchitectureType = (typeof ArchitectureType)[keyof typeof ArchitectureType];
