// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../types";

import * as pulumiAws from "@pulumi/aws";

export namespace aws {
    export interface BastionConfigArgs {
        /**
         * Enable data api. Defaults to `false`
         */
        enabled: pulumi.Input<boolean>;
        /**
         * Public subnet id for the bastion host. You may use`awsx.ec2.Vpc.public_subnet_ids[0]`
         */
        subnetId?: pulumi.Input<string>;
    }

    export interface FunctionScheduleArgs {
        /**
         * Expression for creating a cloudwatch event rule.
         */
        scheduleExpression: pulumi.Input<string>;
        /**
         * Input for cloudwatch event target.
         */
        scheduleInput?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    }

    export interface FunctionUrlArgs {
        /**
         * CORS Configuration.
         */
        corsConfiguration?: pulumi.Input<pulumiAws.types.input.lambda.FunctionUrlCors>;
        /**
         * Use Lambda URL. Defaults to `false`
         */
        urlEnabled?: pulumi.Input<boolean>;
    }
}
