// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../types";

import * as pulumiAws from "@pulumi/aws";

export namespace aws {
    export interface DockerBuildArgs {
        /**
         * Architecture, either `X86_64` or `ARM64`. Defaults to `X86_64`
         */
        architecture?: pulumi.Input<string>;
        /**
         * The path to the build context to use.
         */
        context?: pulumi.Input<string>;
        /**
         * The path to the Dockerfile to use.
         */
        dockerfile?: pulumi.Input<string>;
        /**
         * Environment variables to set on the invocation of docker build, for example to support DOCKER_BUILDKIT=1 docker build.
         */
        env?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        /**
         * A bag of extra options to pass on to the docker SDK.
         */
        extraOptions?: pulumi.Input<pulumi.Input<string>[]>;
        /**
         * The target of the Dockerfile to build
         */
        target?: pulumi.Input<string>;
    }

    export interface FunctionScheduleArgs {
        /**
         * Expression for creating a cloudwatch event rule.
         */
        scheduleExpression: pulumi.Input<string>;
        /**
         * Input for cloudwatch event target.
         */
        scheduleInput?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    }

    export interface FunctionUrlArgs {
        /**
         * CORS Configuration.
         */
        corsConfiguration?: pulumi.Input<pulumiAws.types.input.lambda.FunctionUrlCors>;
        /**
         * Use Lambda URL. Defaults to `false`
         */
        urlEnabled?: pulumi.Input<boolean>;
    }
}
