// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nuage.Aws
{
    [NuageResourceType("nuage:aws:Bastion")]
    public partial class Bastion : Pulumi.ComponentResource
    {
        [Output("private_key_pem")]
        public Output<string> Private_key_pem { get; private set; } = null!;

        [Output("public_ip")]
        public Output<string> Public_ip { get; private set; } = null!;


        /// <summary>
        /// Create a Bastion resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Bastion(string name, BastionArgs args, ComponentResourceOptions? options = null)
            : base("nuage:aws:Bastion", name, args ?? new BastionArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class BastionArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Ssh port for bastion host. Defaults to 22
        /// </summary>
        [Input("sshPort")]
        public Input<double>? SshPort { get; set; }

        /// <summary>
        /// Vpc id.
        /// </summary>
        [Input("vpcId", required: true)]
        public Input<string> VpcId { get; set; } = null!;

        [Input("vpcSubnets", required: true)]
        private InputList<string>? _vpcSubnets;

        /// <summary>
        /// List of subnet ip addresses of Vpc.
        /// </summary>
        public InputList<string> VpcSubnets
        {
            get => _vpcSubnets ?? (_vpcSubnets = new InputList<string>());
            set => _vpcSubnets = value;
        }

        public BastionArgs()
        {
        }
    }
}
