// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nuage.Aws
{
    [NuageResourceType("nuage:aws:Repository")]
    public partial class Repository : Pulumi.ComponentResource
    {
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("registry_id")]
        public Output<string> Registry_id { get; private set; } = null!;

        [Output("repository_arn")]
        public Output<string> Repository_arn { get; private set; } = null!;

        [Output("repository_id")]
        public Output<string> Repository_id { get; private set; } = null!;

        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a Repository resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Repository(string name, RepositoryArgs? args = null, ComponentResourceOptions? options = null)
            : base("nuage:aws:Repository", name, args ?? new RepositoryArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class RepositoryArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Number of days for expiring images using LifecyclePolicy.
        /// </summary>
        [Input("expireInDays")]
        public Input<double>? ExpireInDays { get; set; }

        /// <summary>
        /// Name of the resource.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Name prefix as an alternative to name and adds random suffix at the end.
        /// </summary>
        [Input("namePrefix")]
        public Input<string>? NamePrefix { get; set; }

        public RepositoryArgs()
        {
        }
    }
}
