name: "integration-tests"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.2
        with:
          # Change this to point to your image name
          imageName: ghcr.io/nuage-studio/pulumi-nuage
          # Change this to be your CI task/script
          runCmd: |
            pulumi login
              task test:default
          env: PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_TOKEN }}
