name: "integration-tests"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
    paths:
      - provider/**

env:
  PULUMI_MOUNT_DIR: /home/vscode/.temp_pulumi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create mount directories for the AWS and Pulumai
        run: mkdir ~/.aws

      - name: Run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/nuage-studio/pulumi-nuage
          push: never
          runCmd: |
            pulumi login            
            aws configure set aws_access_key_id  ${{ secrets.AWS_ACCESS_KEY_ID_DEV }} --profile nuage-dev
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }} --profile nuage-dev
            aws configure set region eu-west-1 --profile nuage-dev
            task test:default
          env: |
            PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_TOKEN }}
