// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

import * as pulumiAws from "@pulumi/aws";

export class Bucket_nuage extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'nuage:index:bucket_nuage';

    /**
     * Returns true if the given object is an instance of Bucket_nuage.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Bucket_nuage {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Bucket_nuage.__pulumiType;
    }

    /**
     * The bucket resource.
     */
    public /*out*/ readonly bucket!: pulumi.Output<pulumiAws.s3.Bucket>;

    /**
     * Create a Bucket_nuage resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: Bucket_nuageArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["bucket"] = undefined /*out*/;
        } else {
            resourceInputs["bucket"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Bucket_nuage.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Bucket_nuage resource.
 */
export interface Bucket_nuageArgs {
}
